# This file was generated by GoReleaser. DO NOT EDIT.
cask "iq" do
  version "0.38.0"

  on_macos do
    on_intel do
      sha256 "66efe40413e99bba5368922f5b16fef28b5dd249de464803850c01e4991724d1"
      url "https://github.com/zsltg/iq/releases/download/v#{version}/iq_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d8661a2d2fd5d1b6279be6c9f16f8f6a3aacaafe3552829f0d079ff1a5925cb0"
      url "https://github.com/zsltg/iq/releases/download/v#{version}/iq_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b60eadd8cce7fc7953e1306e56d4031575e9fb0ae96857aaeb92837b031b196d"
      url "https://github.com/zsltg/iq/releases/download/v#{version}/iq_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "541ab8771788bb0782f8c6df2aa8d5b22ba3a58a42514de73c19b3a05914f021"
      url "https://github.com/zsltg/iq/releases/download/v#{version}/iq_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iq"
  desc "jq for NoSQL databases. Use iq to query, dump, copy, diff and write data across Redis, MongoDB, Cassandra, DynamoDB, Elasticsearch, OpenSearch, CouchDB, Couchbase, HBase and Neo4j instances, from a single static binary."
  homepage "https://github.com/zsltg/iq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iq"

  # No zap stanza required

end
